<a href="https://colab.research.google.com/github/minibe0/python-practice/blob/master/numpy_%EA%B8%B0%EB%B3%B8%EC%97%B0%EC%82%B0_08062020.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np
list_data = [1,2,3]
array = np.array(list_data)
print(array.size)
print(array.dtype)
print(array[2])

3
int64
3


0부터 3까지의 배열 만들기


In [0]:
array1=np.arange(4)
print(array1)

array2 = np.zeros((4,4), dtype=float)
print(array2)

array3=np.ones((3,3), dtype=str)
print(array3)

[0 1 2 3]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[['1' '1' '1']
 ['1' '1' '1']
 ['1' '1' '1']]


0부터 9까지   랜덤하게 초기화 된 배열 만들기

In [0]:
array4=np.random.randint(0,10, (3,3))
print(array4)

#평균이 0 이고, 표준편차가 1인 표준 정규를 띄는 배열
array5=np.random.normal(0,1, (3,3))
print(array5)

[[5 7 3]
 [4 3 2]
 [9 5 3]]
[[-0.55525554 -0.06090171  0.17279847]
 [ 0.40002993 -0.12561394  0.68689139]
 [ 0.92870759 -0.23266942 -0.2062757 ]]


In [0]:
array1=np.array([1,2,3])
array2=np.array([4,5,6])
array3=np.concatenate([array1, array2])
print(array3.shape)
print(array3)

(6,)
[1 2 3 4 5 6]


배열 형식 변경하기

In [0]:
import numpy as np
array1=np.array([1,2,3,4])
array2=array1.reshape((2,2))

print(array2)


[[1 2]
 [3 4]]


배열 더하기

In [0]:
array1=np.arange(4).reshape(1,4)
array2=np.arange(8).reshape(2,4)

array3=np.concatenate([array1, array2], axis=0)
print(array3)

[[0 1 2 3]
 [0 1 2 3]
 [4 5 6 7]]


배열 나누기

In [0]:
array =np.arange(8).reshape(2,4)
left, right =np.split(array, [2], axis=1)
print(left.shape)
print(right.shape)
print(left)
print(right)

(2, 2)
(2, 2)
[[0 1 2 3]
 [4 5 6 7]]
[[0 1]
 [4 5]]
[[2 3]
 [6 7]]


In [0]:
array=np.arange(1,5)
array1=array+2
print(array1)

[3 4 5 6]


In [0]:
array=np.arange(1,5)
array1=array*2
print(array1)

[2 4 6 8]


In [0]:
array=np.random.randint(1,10, size=4).reshape(2,2)
print(array)

[[9 5]
 [3 7]]


In [0]:
result_array=array*10
print(result_array)

[[90 50]
 [30 70]]


서로 다른 형태의 배열을 연산할 때 **행우선**으로 수행한다 

broadcasting: 형태가 다른 배열을 연산할 수 있도록 배열의 형태를 동적으로 변환

In [0]:
array1=np.arange(4).reshape(2,2)
array2=np.arange(2)

array3=array1+array2
print(array3)

[[0 2]
 [2 4]]


In [0]:
array=np.arange(0,8).reshape(2,4)
array1=np.arange(0,8).reshape(2,4)
array2=np.concatenate([array,array1], axis=0)
array3=np.arange(0,4).reshape(4,1)
print(array2)
print(array3)
print(array2+array3)

[[0 1 2 3]
 [4 5 6 7]
 [0 1 2 3]
 [4 5 6 7]]
[[0]
 [1]
 [2]
 [3]]
[[ 0  1  2  3]
 [ 5  6  7  8]
 [ 2  3  4  5]
 [ 7  8  9 10]]


마스킹연산: 각 원소에 대하여 체크 ( T or F)

활용예: 이미지 처리 시 특정색상값을 변환(너무 밝은 색상은 다른 색상으로 변경 등)

In [0]:
array1=np.arange(16).reshape(4,4)
print(array1)

array2=array1<10
print(array2)

array1[array2]=100
print(array1)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True False False]
 [False False False False]]
[[100 100 100 100]
 [100 100 100 100]
 [100 100  10  11]
 [ 12  13  14  15]]


집계 연산

최대값 / 최소값/ 평균값 등

In [0]:
array=np.arange(16).reshape(4,4)

print(array)
print("max", np.max(array))
print("min", np.min(array))
print("sum", np.sum(array))
print("avg", np.mean(array))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
max 15
min 0
sum 120
avg 7.5


In [0]:
array=np.arange(16).reshape(4,4)

print(array)
print("sum", np.sum(array, axis=0))
print("sum2", np.sum(array, axis=1))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
sum [24 28 32 36]
sum2 [ 6 22 38 54]
